### ISSUE TITLE
document use of connected?

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/action_cable_client#4]
in my meshchat project, if I make a call to `connected?` I get a really funky error: 

```
/home/webdev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at 'One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0' (JSON::ParserError)
	from /home/webdev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/action_cable_client-1.2.4/lib/action_cable_client.rb:132:in `handle_received_message'
	from /home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/action_cable_client-1.2.4/lib/action_cable_client.rb:78:in `block in received'
	from /home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/em-websocket-client-0.1.2/lib/em-websocket-client.rb:43:in `receive_data'
	from /home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from /home/webdev/Development/meshchat/lib/meshchat.rb:53:in `start'
	from ./run:90:in `<main>'
```

**Comment by NullVoxPopuli** [comment]
confirmed bug with the `connected?` method

**Comment by NullVoxPopuli** [comment]
do I need to switch to Faye? https://github.com/faye/websocket-driver-ruby/blob/master/lib/websocket/driver.rb#L41

**Comment by NullVoxPopuli** [comment]
no need to swap out the web socket engine!

here is how to set/test connectivity

```ruby
        @_client = ActionCableClient.new(path, CHANNEL)

          # don't output anything upon connecting
          _client.connected {
            self._connected = true
          }

          # If there are errors, report them!
          _client.errored do |message|
            process_error(message)
          end

          # forward the encrypted messages to our RequestProcessor
          # so that they can be decrypted
          _client.received do |message|
            process_message(message)
          end

          _client.disconnected do
            self._connected = false
          end

          _client
```

**Comment by NullVoxPopuli** [comment]
should this move inside the gem? or should the connected status be up to the to the user/dev?
